#!/bin/bash

prefix=$1
shift

if [ -e "$prefix" ]; then
    echo "Usage: renumber prefix file1 ... fileN"
    exit 1
fi

while [ $# -gt 0 ]; do
    file=$1
    shift
    dn=${file%/*}
    if [ "$dn" == "$file" ]; then
	dn="";
    else
	dn="$dn/"
    fi
    fn=${file##*/}
    ext="${fn##*.}"
    fwoext="${fn%.*}"
    if [[ "$fwoext" =~ ([0-9]+)x([0-9]{2}) ]]; then
	new_name=$(printf "%s%sS%.2dE%.2d.%s" "$dn" "$prefix" "$(( 10#${BASH_REMATCH[1]} ))" "$(( 10#${BASH_REMATCH[2]} ))" "$ext")
	mv -vi "$file" "$new_name"
    elif [[ "$fwoext" =~ [Ss]([0-9]{2})[Ee]([0-9]{2}) ]]; then
	new_name=$(printf "%s%sS%.2dE%.2d.%s" "$dn" "$prefix" "$(( 10#${BASH_REMATCH[1]} ))" "$(( 10#${BASH_REMATCH[2]} ))" "$ext")
	mv -vi "$file" "$new_name"
    elif [[ "$fwoext" =~ ([0-9]{1})([0-9]{2}) ]]; then
	new_name=$(printf "%s%sS%.2dE%.2d.%s" "$dn" "$prefix" "$(( 10#${BASH_REMATCH[1]} ))" "$(( 10#${BASH_REMATCH[2]} ))" "$ext")
	mv -vi "$file" "$new_name"
    fi
done
